### PR TITLE
enable passing a custom modal-dialog class name

### PR DESCRIPTION
**Pull request by xamoom-pali**
Is there any chance to provide a way of passing a custom CSS class to `<div class="modal-dialog">` in order to enable custom styling?

Imagine a feature where modal dialog is required to look like a mobile phone and thus you would like to change modal's width/height for this specific modal within your app.

The application of the component could look like this:

` {{#bootstrap-modal
close=(action onClose)
closeOnOverlayClick=true
customClassName='preview'}}
...
{{/bootstrap-modal}}`

### CODE REVIEW

**Review by knownasilya — CHANGES_REQUESTED** [review]
Good idea. I think `dialogClass` would fit better,  especially if we want to add custom classes for the overlay.  This also follows the same api as ember power select for custom classes.

**Comment by knownasilya** [comment]
Also could you document it in the readme?

**Review by knownasilya — APPROVED** [review]
Nice, thanks!

**Comment by knownasilya** [comment]
Published as v2.2.0

**Comment by xamoom-pali** [comment]
Thank you!

**Pull request merged**
